---
services:
  redis:
    image: redis:7.2.2-bookworm
    command: redis-server --save 60 1 --loglevel notice --requirepass ${REDIS_PASSWORD-password}
    restart: always
    volumes:
      - cache:/data
    networks:
      - whisper_api_network
    healthcheck:
      test: echo 'auth ${REDIS_PASSWORD-password}\nping' | redis-cli | grep PONG
      interval: 5s
      timeout: 3s
      retries: 5

  api:
    build:
      context: ../src
      dockerfile: Dockerfile
      target: development
    command: flask --app api.app run --host 0.0.0.0 --port 8123 --debug
    environment:
      SECRET_KEY: ${SECRET_KEY-secret}
      REDIS_HOST: ${REDIS_HOST-redis}
      REDIS_PASSWORD: ${REDIS_PASSWORD-password}
    ports:
      - 127.0.0.1:8123:8123
    volumes:
      - ../src:/src
    networks:
      - whisper_api_network
    depends_on:
      redis:
        condition: service_healthy

  worker:
    build:
      context: ../src
      dockerfile: Dockerfile
      target: development
    command: celery -A api.app.celery_app worker --loglevel=debug --concurrency=${WORKER_CONCURRENCY-1}
    environment:
      SECRET_KEY: ${SECRET_KEY-secret}
      REDIS_HOST: ${REDIS_HOST-redis}
      REDIS_PASSWORD: ${REDIS_PASSWORD-password}
    volumes:
      - ../src:/src
    networks:
      - whisper_api_network
    depends_on:
      redis:
        condition: service_healthy
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  flower:
    build:
      context: ../src
      dockerfile: Dockerfile
      target: development
    command: celery --workdir /src -A api.app.celery_app flower --port=5555
    environment:
      SECRET_KEY: ${SECRET_KEY-secret}
      REDIS_HOST: ${REDIS_HOST-redis}
      REDIS_PASSWORD: ${REDIS_PASSWORD-password}
    volumes:
      - ../src:/src
    ports:
      - 127.0.0.1:5555:5555
    networks:
      - whisper_api_network
    depends_on:
      redis:
        condition: service_healthy

volumes:
  cache:

networks:
  whisper_api_network:
